-- AlterTable
ALTER TABLE "company" ALTER COLUMN "company_address" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "company_addresseng" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "company_type" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "company_status" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "company_logo" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "company_stamp" SET DATA TYPE VARCHAR(255);
