-- AlterTable
ALTER TABLE "pr_header" ALTER COLUMN "pr_no" SET DATA TYPE VARCHAR(50),
ALTER COLUMN "status" SET DATA TYPE VARCHAR(30),
ALTER COLUMN "shipping_method" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "vendor_quote_no" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "pr_discount_raw" SET DATA TYPE VARCHAR(30);
